name: ebook
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3 # Untuk menyimpan data lokal
  image_picker: ^1.1.2 # Untuk memilih gambar
  image_picker_for_web: ^3.0.6 # Dukungan untuk web
  provider: ^6.1.2 # Untuk state management
  firebase_core: ^3.9.0 # Inti Firebase
  firebase_auth: ^5.3.4 # Autentikasi Firebase
  cloud_firestore: ^5.6.0 # Database Firestore

dev_dependencies:
  flutter_test:
    sdk: flutter # Untuk pengujian aplikasi
  flutter_lints: ^4.0.0 # Linting kode Flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/selena.png
    - assets/images/Banner.png
    - assets/images/users1.png
    - assets/images/users2.png
    - assets/images/users3.png
    - assets/images/hello.png
    - assets/images/pulangpergi.png
    - assets/images/arahlangkah.png
    - assets/images/gariswaktu.png
    - assets/images/tapakjejak.png
    - assets/images/perahukertas.png
    - assets/images/perihalgendis.png
    - assets/images/segitiga.png
    - assets/images/bumi.png
    - assets/images/bulan.png
    - assets/images/matahari.png
    - assets/images/buyahamka.png
    - assets/images/anakrantau.png
    - assets/images/komsikomsa.png
    - assets/images/laskarpelangi.png

  # Uncomment and update font settings if needed in the future
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
