// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAQa6jy0g299tgoNrpH9Oba98eLEsSOGw',
    appId: '1:454048955186:web:9d08c866d831c978be352b',
    messagingSenderId: '454048955186',
    projectId: 'ebook22',
    authDomain: 'ebook22.firebaseapp.com',
    storageBucket: 'ebook22.firebasestorage.app',
    measurementId: 'G-TEJXNDRCY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGQ5Sw_r2vyDAXsbCQpEmnBUfhlZBiZFg',
    appId: '1:454048955186:android:f336fa0768b9d0c3be352b',
    messagingSenderId: '454048955186',
    projectId: 'ebook22',
    storageBucket: 'ebook22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPj_jWavU8xPVoRXYKdabZYwQPV1Vl9xE',
    appId: '1:454048955186:ios:04eece8411f7a487be352b',
    messagingSenderId: '454048955186',
    projectId: 'ebook22',
    storageBucket: 'ebook22.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );
}
